from pygame import QUIT as QUIT
from pygame import RESIZABLE as RESIZABLE
from pygame import USEREVENT as USEREVENT
from pygame import WINDOWRESIZED as WINDOWRESIZED
from pygame import Surface as Surface
from pygame import display as display
from pygame import event as event
from pygame import image as image
from pygame import init as init
from pygame import key as key
from pygame import math as math
from pygame import quit as quit
from pygame import sprite as sprite
from pygame import time as time
from pygame import transform as transform
